name: Run lint, tests and build
on: [push,pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-node@v1
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: yarn install
    - name: Run lint, tests and build
      run: yarn build
